# Generated by Django 5.0.3 on 2024-04-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0002_delete_note_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('lastEdited', models.DateTimeField()),
                ('dateCreated', models.DateTimeField()),
                ('linkedFrom', models.ManyToManyField(to='notes.note')),
                ('linkedTo', models.ManyToManyField(to='notes.note')),
                ('tags', models.ManyToManyField(to='notes.tag')),
            ],
        ),
    ]
