# Generated by Django 5.0.3 on 2024-04-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='linkedFrom',
            field=models.ManyToManyField(null=True, to='notes.note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='linkedTo',
            field=models.ManyToManyField(null=True, to='notes.note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(null=True, to='notes.tag'),
        ),
    ]
