# Imagen base con Maven para la compilación
FROM maven:3.6.3-jdk-11 as build

# Copiar los archivos del proyecto
COPY src /app/src
COPY pom.xml /app

# Establecer el directorio de trabajo
WORKDIR /app

# Compilar y empaquetar la aplicación
RUN mvn clean package

# Imagen base para la ejecución
FROM openjdk:11-jre-slim

# Copiar el JAR compilado al contenedor
COPY --from=build /app/target/*.jar /app/app.jar

# Exponer el puerto usado por la aplicación
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["java", "-jar", "/app/app.jar"]
