# Imagen base con Node.js
FROM node:14 as build

# Establecer el directorio de trabajo
WORKDIR /app

# Instalar dependencias
COPY package*.json ./
RUN npm install

# Construir la aplicación
COPY . .
RUN npm run build

# Imagen base para la ejecución
FROM nginx:alpine

# Copiar los archivos estáticos al servidor Nginx
COPY --from=build /app/public /usr/share/nginx/html

# Exponer el puerto del servidor web
EXPOSE 80

# Comando para ejecutar Nginx
CMD ["nginx", "-g", "daemon off;"]
